/*INSERTS WORLDS */
INSERT INTO WORLD (NAME, HABITABLE) VALUES('Erde', TRUE);
INSERT INTO WORLD (NAME, HABITABLE) VALUES('Wunderland', TRUE);
INSERT INTO WORLD (NAME, HABITABLE) VALUES('Mars', False);